/** Route inventory for BE-024. Must match docs/MVP-ROADMAP.md §4.6 (plus BE-050–056). */

export type HttpMethod = "get" | "post" | "patch" | "put" | "delete";

export type ContractRoute = {
  ticket: string;
  method: HttpMethod;
  path: string;
};

export const API_CONTRACT_ROUTES: ContractRoute[] = [
  { ticket: "BE-030", method: "get", path: "/api/public/sessions" },
  { ticket: "BE-030", method: "get", path: "/api/public/sessions/{id}" },
  { ticket: "BE-030", method: "get", path: "/api/public/coaches" },
  { ticket: "BE-030", method: "get", path: "/api/public/classes" },
  { ticket: "BE-030", method: "get", path: "/api/public/content" },
  { ticket: "BE-031", method: "get", path: "/api/me" },
  { ticket: "BE-031", method: "patch", path: "/api/me" },
  { ticket: "BE-031", method: "get", path: "/api/me/policy-acceptances" },
  { ticket: "BE-032", method: "post", path: "/api/bookings" },
  { ticket: "BE-032", method: "post", path: "/api/bookings/{id}/waitlist" },
  { ticket: "BE-032", method: "get", path: "/api/bookings" },
  { ticket: "BE-032", method: "get", path: "/api/bookings/{id}" },
  { ticket: "BE-033", method: "post", path: "/api/bookings/{id}/payment-method" },
  { ticket: "BE-033", method: "post", path: "/api/bookings/{id}/payment-proof" },
  { ticket: "BE-033", method: "get", path: "/api/payment-instructions" },
  { ticket: "BE-034", method: "post", path: "/api/bookings/{id}/cancellation-request" },
  { ticket: "BE-035", method: "post", path: "/api/bookings/{id}/reschedule-request" },
  { ticket: "BE-036", method: "get", path: "/api/admin/bookings" },
  { ticket: "BE-036", method: "post", path: "/api/admin/bookings/{id}/confirm" },
  { ticket: "BE-036", method: "post", path: "/api/admin/bookings/{id}/reject" },
  { ticket: "BE-037", method: "get", path: "/api/admin/payments" },
  { ticket: "BE-037", method: "get", path: "/api/admin/payment-proofs/{id}/signed-url" },
  { ticket: "BE-037", method: "post", path: "/api/admin/payments/{id}/record-cash" },
  { ticket: "BE-037", method: "post", path: "/api/admin/refunds/{id}/mark-pending" },
  { ticket: "BE-037", method: "post", path: "/api/admin/refunds/{id}/mark-refunded" },
  { ticket: "BE-038", method: "get", path: "/api/admin/classes" },
  { ticket: "BE-038", method: "post", path: "/api/admin/classes" },
  { ticket: "BE-038", method: "patch", path: "/api/admin/classes/{id}" },
  { ticket: "BE-038", method: "get", path: "/api/admin/coaches" },
  { ticket: "BE-038", method: "post", path: "/api/admin/coaches" },
  { ticket: "BE-038", method: "patch", path: "/api/admin/coaches/{id}" },
  { ticket: "BE-038", method: "post", path: "/api/admin/coaches/{id}/photo" },
  { ticket: "BE-038", method: "delete", path: "/api/admin/coaches/{id}/photo" },
  { ticket: "BE-038", method: "get", path: "/api/admin/sessions" },
  { ticket: "BE-038", method: "post", path: "/api/admin/sessions" },
  { ticket: "BE-057", method: "post", path: "/api/admin/sessions/duplicate" },
  { ticket: "BE-038", method: "patch", path: "/api/admin/sessions/{id}" },
  { ticket: "BE-057", method: "post", path: "/api/admin/sessions/{id}/recurrence" },
  { ticket: "BE-038", method: "post", path: "/api/admin/sessions/{id}/cancel" },
  { ticket: "BE-039", method: "get", path: "/api/admin/cancellation-requests" },
  { ticket: "BE-039", method: "post", path: "/api/admin/cancellation-requests/{id}/complete" },
  { ticket: "BE-039", method: "post", path: "/api/admin/cancellation-requests/{id}/reject" },
  { ticket: "BE-039", method: "get", path: "/api/admin/reschedule-requests" },
  { ticket: "BE-039", method: "post", path: "/api/admin/reschedule-requests/{id}/approve" },
  { ticket: "BE-039", method: "post", path: "/api/admin/reschedule-requests/{id}/reject" },
  { ticket: "BE-040", method: "get", path: "/api/admin/sessions/{id}/roster" },
  { ticket: "BE-040", method: "post", path: "/api/admin/sessions/{id}/check-in" },
  { ticket: "BE-040", method: "post", path: "/api/admin/sessions/{id}/no-show" },
  { ticket: "BE-041", method: "get", path: "/api/admin/reports/sales-overview" },
  { ticket: "BE-041", method: "get", path: "/api/admin/reports/class-performance" },
  { ticket: "BE-041", method: "get", path: "/api/admin/reports/coach-costs" },
  { ticket: "BE-041", method: "get", path: "/api/admin/reports/session-performance" },
  { ticket: "BE-041", method: "get", path: "/api/admin/reports/sessions/{id}" },
  { ticket: "BE-042", method: "get", path: "/api/admin/staff" },
  { ticket: "BE-042", method: "post", path: "/api/admin/staff" },
  { ticket: "BE-042", method: "patch", path: "/api/admin/staff/{id}" },
  { ticket: "BE-042", method: "post", path: "/api/admin/staff/{id}/disable" },
  { ticket: "BE-055", method: "post", path: "/api/admin/staff/{id}/coach" },
  { ticket: "BE-055", method: "delete", path: "/api/admin/staff/{id}/coach" },
  { ticket: "BE-042", method: "get", path: "/api/admin/customers" },
  { ticket: "BE-042", method: "get", path: "/api/admin/customers/{id}" },
  { ticket: "BE-043", method: "get", path: "/api/admin/settings" },
  { ticket: "BE-043", method: "patch", path: "/api/admin/settings" },
  { ticket: "BE-052", method: "post", path: "/api/admin/settings/qr" },
  { ticket: "BE-052", method: "delete", path: "/api/admin/settings/qr" },
  { ticket: "BE-053", method: "post", path: "/api/admin/settings/faqs" },
  { ticket: "BE-053", method: "patch", path: "/api/admin/settings/faqs/{id}" },
  { ticket: "BE-053", method: "delete", path: "/api/admin/settings/faqs/{id}" },
  { ticket: "BE-053", method: "post", path: "/api/admin/settings/faqs/reorder" },
  { ticket: "BE-053", method: "post", path: "/api/admin/settings/policies/{id}/promote" },
  { ticket: "BE-054", method: "get", path: "/api/admin/dashboard" },
  { ticket: "BE-054", method: "get", path: "/api/admin/dashboard/metrics" },
  { ticket: "BE-056", method: "get", path: "/api/admin/settings/payment-qrs" },
  { ticket: "BE-056", method: "post", path: "/api/admin/settings/payment-qrs" },
  { ticket: "BE-056", method: "patch", path: "/api/admin/settings/payment-qrs/{id}" },
  { ticket: "BE-056", method: "post", path: "/api/admin/settings/payment-qrs/{id}/activate" },
  { ticket: "BE-056", method: "delete", path: "/api/admin/settings/payment-qrs/{id}" },
];
